version: '3'

services:
  opensearch:
    image: opensearchproject/opensearch:1.3.9
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    volumes:
      - ./opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks: [my_net]

  mitre-ingest:
    image: python:3.9-slim
    container_name: mitre-ingest
    depends_on: [opensearch]
    volumes:
      - ./mitre/enterprise-attack.json:/data/enterprise-attack.json:ro
      - ./ingest_mitre.py:/ingest_mitre.py:ro
    entrypoint: ["sh","-c"]
    command: |
      pip install --no-cache-dir opensearch-py && \
      python /ingest_mitre.py
    networks: [my_net]

  cortex:
    build:
      context: .
      dockerfile: Dockerfile.cortex
    depends_on: [opensearch]
    environment:
      - JOB_DIRECTORY=/tmp/cortex-jobs
    command: ["--es-uri","http://opensearch:9200"]
    volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf:ro
      - ./cortex/logback.xml:/etc/cortex/logback.xml:ro
      - /home/vboxuser/Cortex-Analyzers/analyzers:/opt/Cortex-Analyzers/analyzers:ro
    ports:
      - "9001:9001"
    networks: [my_net]

  thehive:
    image: thehiveproject/thehive:latest
    depends_on: [opensearch, cortex]
    command: ["--es-uri","http://opensearch:9200","--auto-migration"]
    volumes:
      - ./thehive-config:/etc/thehive:ro
    ports:
      - "9000:9000"
    networks: [my_net]

  dashboards:
    image: opensearchproject/opensearch-dashboards:1.3.9
    depends_on: [opensearch]
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      OPENSEARCH_SSL_VERIFICATION_MODE: none
      DASHBOARDS_SECURITY_ENABLED: "false"
      OPENSEARCH_SECURITY_MULTITENANCY_ENABLED: "false"
      OPENSEARCH_SECURITY_MULTITENANCY_ENABLED_BY_DEFAULT: "false"
      OPENSEARCH_SECURITY_READONLY_MODE_ROLES: "[]"
    ports:
      - "5601:5601"
    networks: [my_net]

  web:
    build:
      context: ./web           #  ← carpeta donde está Dockerfile
    env_file:
      - ./web/.env             #  ← variables: PORT, CORTEX_URL, CORTEX_API_KEY
    depends_on:
      - cortex
      - opensearch
    ports:
      - "8080:8080"            #  host:contenedor
    networks:
      - my_net                 #  misma red que el resto

networks:
  my_net:
    driver: bridge
